name: Run Twitter Bot Workflow

# This allows you to run the workflow manually from the Actions tab in GitHub.
on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          # Install Python packages
          python -m pip install --upgrade pip
          pip install playwright supabase python-dotenv pytz
          
          # Ensure git is installed (for cloning the OTP repo)
          sudo apt-get update && sudo apt-get install -y git

      - name: 4. Install Playwright browser dependencies
        run: python -m playwright install chromium

      - name: 5. Run the Main Bot Controller
        # This step executes the main script.
        # You must configure all the secrets listed in the 'env' section below.
        # Go to your repo > Settings > Secrets and variables > Actions > New repository secret.
        env:
          # Supabase Credentials
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

          # Formula Bot Credentials
          FORMULA_EMAIL: ${{ secrets.FORMULA_EMAIL }}
          FORMULA_USERNAME: ${{ secrets.FORMULA_USERNAME }}
          FORMULA_PASSWORD: ${{ secrets.FORMULA_PASSWORD }}

          # Tech Bot Credentials
          TECH_EMAIL: ${{ secrets.TECH_EMAIL }}
          TECH_USERNAME: ${{ secrets.TECH_USERNAME }}
          TECH_PASSWORD: ${{ secrets.TECH_PASSWORD }}
          
          # Hollywood Bot Credentials
          HOLLYWOOD_EMAIL: ${{ secrets.HOLLYWOOD_EMAIL }}
          HOLLYWOOD_USERNAME: ${{ secrets.HOLLYWOOD_USERNAME }}
          HOLLYWOOD_PASSWORD: ${{ secrets.HOLLYWOOD_PASSWORD }}
          
          # Movies Bot Credentials
          MOVIES_EMAIL: ${{ secrets.MOVIES_EMAIL }}
          MOVIES_USERNAME: ${{ secrets.MOVIES_USERNAME }}
          MOVIES_PASSWORD: ${{ secrets.MOVIES_PASSWORD }}
          
          # Unews Bot Credentials
          UNEWS_EMAIL: ${{ secrets.UNEWS_EMAIL }}
          UNEWS_USERNAME: ${{ secrets.UNEWS_USERNAME }}
          UNEWS_PASSWORD: ${{ secrets.UNEWS_PASSWORD }}
          
          # News Bot Credentials
          NEWS_EMAIL: ${{ secrets.NEWS_EMAIL }}
          NEWS_USERNAME: ${{ secrets.NEWS_USERNAME }}
          NEWS_PASSWORD: ${{ secrets.NEWS_PASSWORD }}
          
        run: python old_stuff/main_controller.py
