name: Debug Formula Login

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-formula-login:
    runs-on: ubuntu-latest
    
    env:
      TWITTER_EMAIL: ${{ secrets.FORMULA_EMAIL }}
      TWITTER_USERNAME: ${{ secrets.FORMULA_USERNAME }}
      TWITTER_PASSWORD: ${{ secrets.FORMULA_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium

      # Run the script. If it fails, continue anyway so we can commit screenshots.
      - name: Run Formula Login Script
        run: python formula/login.py || true

      # NEW STEP: Commit the screenshots folder.
      - name: Commit Debug Screenshots
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          
          # Add the screenshots folder. Use "|| true" in case it wasn't created.
          git add debug_screenshots/ || true
          
          # Check if there are any changes to commit.
          if ! git diff --staged --quiet; then
            echo "Changes detected in debug_screenshots. Committing..."
            git commit -m "chore: Add debug screenshots from formula login test"
            git push
          else
            echo "No new screenshots to commit."
          fi
