name: Twitter Bot Scheduler

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-twitter-bots:
    runs-on: ubuntu-latest
    
    env:
      # ... (Your secrets remain the same)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      FORMULA_EMAIL: ${{ secrets.FORMULA_EMAIL }}
      # ... etc.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium

      # Run the controller. If it fails, we continue anyway to commit the screenshots.
      - name: Run Main Bot Controller
        run: python main_controller.py || true

      # This is the new, simplified commit step.
      - name: Commit session data and debug screenshots
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          
          # Add both the session data and the new screenshots folder
          git add '*/login_data/'
          git add debug_screenshots/
          
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing..."
            git commit -m "chore: Update session and debug screenshots [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
