name: Run NEW Bot Workflow and Save Data

on:
  workflow_dispatch:

jobs:
  run-and-save-bots:
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # Grant the GITHUB_TOKEN write permission to commit back to the repo
    permissions:
      contents: write

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright supabase python-dotenv pytz GitPython

      - name: 4. Install Playwright browser dependencies
        run: python -m playwright install chromium

      - name: 5. Run the Main Bot Controller
        env:
          # Supabase Credentials
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

          # --- All Bot Credentials ---
          FORMULA_EMAIL: ${{ secrets.FORMULA_EMAIL }}
          FORMULA_USERNAME: ${{ secrets.FORMULA_USERNAME }}
          FORMULA_PASSWORD: ${{ secrets.FORMULA_PASSWORD }}
          TECH_EMAIL: ${{ secrets.TECH_EMAIL }}
          TECH_USERNAME: ${{ secrets.TECH_USERNAME }}
          TECH_PASSWORD: ${{ secrets.TECH_PASSWORD }}
          HOLLYWOOD_EMAIL: ${{ secrets.HOLLYWOOD_EMAIL }}
          HOLLYWOOD_USERNAME: ${{ secrets.HOLLYWOOD_USERNAME }}
          HOLLYWOOD_PASSWORD: ${{ secrets.HOLLYWOOD_PASSWORD }}
          MOVIES_EMAIL: ${{ secrets.MOVIES_EMAIL }}
          MOVIES_USERNAME: ${{ secrets.MOVIES_USERNAME }}
          MOVIES_PASSWORD: ${{ secrets.MOVIES_PASSWORD }}
          UNEWS_EMAIL: ${{ secrets.UNEWS_EMAIL }}
          UNEWS_USERNAME: ${{ secrets.UNEWS_USERNAME }}
          UNEWS_PASSWORD: ${{ secrets.UNEWS_PASSWORD }}
          NEWS_EMAIL: ${{ secrets.NEWS_EMAIL }}
          NEWS_USERNAME: ${{ secrets.NEWS_USERNAME }}
          NEWS_PASSWORD: ${{ secrets.NEWS_PASSWORD }}
        
        working-directory: ./new_stuff
        run: python main_controller.py

      - name: 6. Commit and Push Session Data & Logs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Update session data and debug logs"
