name: Run NEW Bot Workflow and Save Data

# This allows you to run the workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  run-and-save-bots:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install all dependencies
        run: |
          python -m pip install --upgrade pip
          # Added GitPython for the login script
          pip install playwright supabase python-dotenv pytz GitPython

      - name: 4. Install Playwright browser dependencies
        run: python -m playwright install chromium

      - name: 5. Run the Main Bot Controller
        # This step runs the main script from within the new_stuff directory.
        # This is CRITICAL because all the paths inside your scripts are relative.
        env:
          # Supabase Credentials
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

          # --- All Bot Credentials ---
          FORMULA_EMAIL: ${{ secrets.FORMULA_EMAIL }}
          FORMULA_USERNAME: ${{ secrets.FORMULA_USERNAME }}
          FORMULA_PASSWORD: ${{ secrets.FORMULA_PASSWORD }}
          TECH_EMAIL: ${{ secrets.TECH_EMAIL }}
          TECH_USERNAME: ${{ secrets.TECH_USERNAME }}
          TECH_PASSWORD: ${{ secrets.TECH_PASSWORD }}
          HOLLYWOOD_EMAIL: ${{ secrets.HOLLYWOOD_EMAIL }}
          HOLLYWOOD_USERNAME: ${{ secrets.HOLLYWOOD_USERNAME }}
          HOLLYWOOD_PASSWORD: ${{ secrets.HOLLYWOOD_PASSWORD }}
          MOVIES_EMAIL: ${{ secrets.MOVIES_EMAIL }}
          MOVIES_USERNAME: ${{ secrets.MOVIES_USERNAME }}
          MOVIES_PASSWORD: ${{ secrets.MOVIES_PASSWORD }}
          UNEWS_EMAIL: ${{ secrets.UNEWS_EMAIL }}
          UNEWS_USERNAME: ${{ secrets.UNEWS_USERNAME }}
          UNEWS_PASSWORD: ${{ secrets.UNEWS_PASSWORD }}
          NEWS_EMAIL: ${{ secrets.NEWS_EMAIL }}
          NEWS_USERNAME: ${{ secrets.NEWS_USERNAME }}
          NEWS_PASSWORD: ${{ secrets.NEWS_PASSWORD }}
        
        # We set the working directory here so the script can find all its files
        working_directory: ./new_stuff
        run: python main_controller.py

      - name: 6. Commit and Push Session Data & Logs
        # This action automatically finds any new or modified files and commits them.
        # It's how the login data and screenshots get saved back to your repo.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "BOT: Update session data and debug logs"
          # This will add all new/modified files (like login_data/ and debug_screenshots/)
          # and push them back to the branch the workflow was run on.
